import { CreateOrderT } from "@/types/order";
import { CreateOrderItemT } from "@/types/orderItem";
import { UserI } from "@/shared-types";
import { TshirtType } from "@/features/dashboard/selectTshirt";

interface OrderPayloadParams {
  user: UserI;
  selectedTshirt: TshirtType;
  generatedImageUrl: string;
  productImageUrl?: string;
  productId?: string;
}

interface OrderWithItemsPayload {
  order: Omit<CreateOrderT, 'order_number'>;
  orderItem: Omit<CreateOrderItemT, 'order_id'>;
}

/**
 * Creates order payload with data available at product selection step
 * Payment and pricing details will be added in later steps
 */
export function useOrderPayload() {
  const create = ({
    user,
    selectedTshirt,
    generatedImageUrl,
    productImageUrl,
    productId,
  }: OrderPayloadParams): OrderWithItemsPayload => {
    // Get customer name from user metadata
    const firstName = user.user_metadata?.first_name || '';
    const lastName = user.user_metadata?.last_name || '';
    const customerName = `${firstName} ${lastName}`.trim() || undefined;

    // Store minimal metadata in internal_notes (for backward compatibility)
    const orderMetadata = {
      printify_product_id: productId,
      tshirt: {
        id: selectedTshirt.id,
        name: selectedTshirt.name,
        blueprint_id: selectedTshirt.blueprint_id,
        print_provider_id: selectedTshirt.print_provider_id,
      },
    };

    // Default pricing (will be updated during payment)
    const defaultPrice = 25.0;
    const quantity = 1;

    const order: Omit<CreateOrderT, 'order_number'> = {
      // Required fields
      customer_email: user.email,
      // Note: order_number will be generated by the database function

      // Customer information
      customer_name: customerName,
      user_id: user.id,

      // Store Printify product ID
      product_id: productId || null,

      // Store minimal metadata in internal_notes
      internal_notes: JSON.stringify(orderMetadata),

      // Pricing (will be updated in payment step)
      subtotal: defaultPrice,
      shipping_cost: 5.99,
      total_amount: defaultPrice + 5.99,

      // Status fields - order is created but pending payment
      status: 'pending',
      fulfillment_status: 'unfulfilled',
      payment_status: 'pending',
    };

    const orderItem: Omit<CreateOrderItemT, 'order_id'> = {
      // Product information - store Printify product ID
      product_id: productId || null,
      product_name: `${selectedTshirt.name} - Custom Design`,
      variant_name: selectedTshirt.name,
      variant_id: null, // Will be set during checkout when variant is selected

      // Image URL - this is what we'll display in the order summary
      custom_image_url: productImageUrl || generatedImageUrl,

      // Pricing
      quantity: quantity,
      unit_price: defaultPrice,
      total_price: defaultPrice * quantity,

      // Design configuration
      design_config: {
        printify_product_id: productId,
        tshirt_type: selectedTshirt.id,
        generated_image_url: generatedImageUrl,
        product_image_url: productImageUrl,
        blueprint_id: selectedTshirt.blueprint_id,
        print_provider_id: selectedTshirt.print_provider_id,
      },

      // Status
      fulfillment_status: 'unfulfilled',
    };

    return {
      order,
      orderItem,
    };
  };

  return { create };
}
